//
// Created by tyler on 9/29/17.
//

#ifndef YAFEL_YAFEL_CONFIG_HPP
#define YAFEL_YAFEL_CONFIG_HPP

#include "yafel_globals.hpp"

YAFEL_NAMESPACE_OPEN

namespace config {

/**
 * Number of bytes per cache line. 64 is a reasonable guess,
 * but configure to taste.
 */
constexpr int cacheline_bytes = 64;

/**
 * Number of cores on the machine. Used in initializing the
 * global TaskScheduler. Default to 8 if not defined.
 */
extern const int num_cores;
//#ifndef NUM_CPU_CORES
//#define NUM_CPU_CORES 8
//constexpr int num_cores = 8;
//#else
//constexpr int num_cores = NUM_CPU_CORES;
//#endif



///@{
/**
 * Information about the YAFEL compilation, generated by CMake
 */
const extern std::string VERSION;
const extern std::string BUILD_TYPE;
///@}

} //end namespace config

YAFEL_NAMESPACE_CLOSE

#endif //YAFEL_YAFEL_CONFIG_HPP
